
name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain update nightly && rustup default nightly && rustup component add clippy && cargo install cargo-tarpaulin
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy + code coverage generation
      run: cargo clippy -- -D warnings && cargo +nightly tarpaulin --verbose --all-features --ignore-tests --engine llvm --workspace -exclude pluginop-wasm --exclude-files lib.rs main.rs mod.rs --out Xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
